sonar.projectKey=Yagna226522622_8.2CDevSecOps
sonar.organization=yagna226522622
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=node_modules/**,test/**,**/build-wrapper-dump.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.nodejs.executable=/opt/node24/bin/node

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
